// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    Activity: typeof import('./src/components/HomeComps/Activity/index.vue')['default']
    Carousel: typeof import('./src/components/HomeComps/Carousel/index.vue')['default']
    Communication: typeof import('./src/components/HomeComps/Communication/index.vue')['default']
    Content: typeof import('./src/components/ContainerComps/Content/index.vue')['default']
    Drawer: typeof import('./src/components/ContainerComps/Header/Drawer/index.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCard: typeof import('element-plus/es')['ElCard']
    ElCarousel: typeof import('element-plus/es')['ElCarousel']
    ElCarouselItem: typeof import('element-plus/es')['ElCarouselItem']
    ElCol: typeof import('element-plus/es')['ElCol']
    ElDrawer: typeof import('element-plus/es')['ElDrawer']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElMenu: typeof import('element-plus/es')['ElMenu']
    ElMenuItem: typeof import('element-plus/es')['ElMenuItem']
    ElPopconfirm: typeof import('element-plus/es')['ElPopconfirm']
    ElRadio: typeof import('element-plus/es')['ElRadio']
    ElRow: typeof import('element-plus/es')['ElRow']
    ElSwitch: typeof import('element-plus/es')['ElSwitch']
    ElUpload: typeof import('element-plus/es')['ElUpload']
    Footer: typeof import('./src/components/ContainerComps/Footer/index.vue')['default']
    Form: typeof import('./src/components/CommonComps/Form/index.vue')['default']
    Header: typeof import('./src/components/ContainerComps/Header/index.vue')['default']
    HomeComps: typeof import('./src/components/HomeComps/index.vue')['default']
    Introduction: typeof import('./src/components/HomeComps/Introduction/index.vue')['default']
    Layout: typeof import('./src/components/ContainerComps/Layout/layout.vue')['default']
    Serve: typeof import('./src/components/HomeComps/Serve/index.vue')['default']
    Suggestion: typeof import('./src/components/HomeComps/Suggestion/index.vue')['default']
    UploadAvatar: typeof import('./src/components/CommonComps/UploadAvatar/index.vue')['default']
  }
}

export { }
