// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    Content: typeof import('./src/components/ContainerComps/Content/index.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElMenu: typeof import('element-plus/es')['ElMenu']
    ElMenuItem: typeof import('element-plus/es')['ElMenuItem']
    ElRow: typeof import('element-plus/es')['ElRow']
    ElSubMenu: typeof import('element-plus/es')['ElSubMenu']
    Footer: typeof import('./src/components/ContainerComps/Footer/index.vue')['default']
    Header: typeof import('./src/components/ContainerComps/Header/index.vue')['default']
    Layout: typeof import('./src/components/ContainerComps/Layout/layout.vue')['default']
    LoginForm: typeof import('./src/components/CommonComps/LoginForm/index.vue')['default']
  }
}

export { }
