// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    Content: typeof import('./src/components/ContainerComps/Content/index.vue')['default']
    Footer: typeof import('./src/components/ContainerComps/Footer/index.vue')['default']
    Header: typeof import('./src/components/ContainerComps/Header/index.vue')['default']
    Layout: typeof import('./src/components/ContainerComps/Layout/layout.vue')['default']
    TButton: typeof import('tdesign-vue-next')['Button']
    TComment: typeof import('tdesign-vue-next')['Comment']
    THeadMenu: typeof import('tdesign-vue-next')['HeadMenu']
    TIcon: typeof import('tdesign-vue-next')['Icon']
    TMenuItem: typeof import('tdesign-vue-next')['MenuItem']
  }
}

export { }
